CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price_in_cents INT NOT NULL
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_in_cents INT NOT NULL DEFAULT 0
);

CREATE TABLE recipe_products (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    PRIMARY KEY (recipe_id, product_id)
);

CREATE TABLE cart_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(id),
    recipe_id BIGINT NOT NULL REFERENCES recipes(id),
    quantity INT NOT NULL DEFAULT 1,
    UNIQUE (cart_id, recipe_id)
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INT NOT NULL DEFAULT 1,
    UNIQUE (cart_id, product_id)
);